### ISSUE TITLE
Hi from Jellyfin

### ISSUE THREAD

**Issue by anthonylavado** [eebette/Jellyfin-Tools#6]
Hey there, I'm on the Jellyfin Core Team and just wanted to say thanks for this utility. I've been using it myself and it's been great.

**Comment by eebette** [comment]
Hey!

No problem at all, I'm happy to contribute to the community.

I love Jellyfin and am looking for opportunities to help out, so please let me know if there's any chances to help out!

Best regards,

Eric
------- Original Message -------
